# Generated by Django 3.1.5 on 2021-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
